spring:
  application:
    name: users
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  flyway:
    enabled: false

  data:
    redis:
      cluster:
        nodes:
          - ${server.url}:${redis_master.port1},
          - ${server.url}:${redis_master.port2},
          - ${server.url}:${redis_master.port3},
        max-redirects: 3
  cache:
    type: redis
    redis:
      enable-statistics: true

custom:
  flyway:
    business:
      locations: classpath:db/migration
      baseline-on-migrate: true
    batch:
      locations: classpath:db/migration_batch
      baseline-on-migrate: true

  jpa:
    entity-scan-packages:
      - com.msa.userserver.domain.entity
