spring:
  application:
    name: users
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 30
      connection-timeout: 5000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

custom:
  flyway:
    business:
      locations: classpath:db/migration
      baseline-on-migrate: true
    batch:
      locations: classpath:db/migration_batch
      baseline-on-migrate: true

  jpa:
    entity-scan-packages:
      - com.msa.userserver.domain.entity
