spring:
  application:
    name: order
  profiles:
    active: dev
  config:
    import: optional:application-secret.properties

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  kafka:
    listener:
      missing-topics-fatal: false
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka.uri}
  cloud:
    bus:
      ack:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        show_sql: true
        format_sql: true

#  data:
#    redis:
#      cluster:
#        nodes:
#          - ${server.url}:${redis_master.port1},
#          - ${server.url}:${redis_master.port2},
#          - ${server.url}:${redis_master.port3},
#        max-redirects: 3
#  cache:
#    type: redis
#    redis:
#      enable-statistics: true

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.kafka.retrytopic: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh

custom:
  flyway:
    business:
      locations: classpath:db/migration
      baseline-on-migrate: true
    batch:
      locations: classpath:db/migration_batch
      baseline-on-migrate: true

  jpa:
    entity-scan-packages:
      - com.msa.order
qz:
  private-key: ${qz.private-key}