spring:
  application:
    name: account
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.orm.internal.util.LogHelper: DEBUG
    org.springframework.orm.jpa: DEBUG

custom:
  datasource:
    db-name: accountdb

  jpa:
    entity-scan-packages:
      - com.account.domain.store.entity
      - com.account.domain.factory.entity
      - com.account.global.domain.entity
